import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Chocolate Pecan Cookies 160gm',
    description: 'Rich buttery dough loaded with crunchy pecans and dark chocolate chunks.',
    price: 29.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Pecans', 'Dark Chocolate', 'Butter', 'Flour', 'Brown Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1YCJFIHNzRPbWddO568ZSscIoqrzY9YUi',
    inStock: true,
    stockCount: 45,
  },
  {
    id: '2',
    name: 'Walnut Oatmeal Cookies 160gm',
    description: 'Crisp and crumbly cookies packed with roasted walnuts and hearty oatmeal.',
    price: 29.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Walnuts', 'Rolled Oats', 'Butter', 'Flour', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1O2LGJi0RjJ_sNV5Poe095J0mqn9pjevE',
    inStock: true,
    stockCount: 30,
  },
  {
    id: '3',
    name: 'Pineapple Jam Tart 350gm',
    description: 'Golden, bite-sized pastry balls filled with homemade caramelized pineapple jam.',
    price: 38.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Pineapple Jam', 'Butter', 'Flour', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1rBX1B9igHk6ky-ecIYmV7ulsR1y3Orrh',
    inStock: true,
    stockCount: 25,
  },
  {
    id: '4',
    name: 'Golden Pineapple Cake (8pcs) 300gm',
    description: 'Traditional square shortcrust pastry encasing a generous filling of sweet and tangy pineapple paste.',
    price: 42.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Pineapple Paste', 'Butter', 'Flour', 'Milk Powder', 'Cheese Powder'],
    image: 'https://lh3.googleusercontent.com/d/1oE2yfoUvnOpf6ExdaVOIXGRAkKFFwdMP',
    inStock: true,
    stockCount: 20,
  },
  {
    id: '5',
    name: 'Mixed Nut Tart (12pcs) 240gm',
    description: 'A crunchy tart shell filled with a caramelized blend of macadamias, almonds, walnuts, pumpkin seeds, and cranberries.',
    price: 48.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Macadamia', 'Almond', 'Walnut', 'Cranberry', 'Pumpkin Seeds', 'Caramel'],
    image: 'https://lh3.googleusercontent.com/d/14Z3OrMcMJjWIeGg6XCHbeV9_uTFs5W9l',
    inStock: true,
    stockCount: 15,
  },
  {
    id: '6',
    name: 'Organic Passion Cranberry Cookies 180gm',
    description: 'Tangy organic passion fruit combined with chewy cranberries for a refreshing, fruity cookie.',
    price: 29.00,
    category: 'Vegan',
    ingredients: ['Organic Passion Fruit', 'Dried Cranberries', 'Organic Flour', 'Butter'],
    image: 'https://lh3.googleusercontent.com/d/1zTdNJdLUP1dyWhLl9QJbx6-gsacvI59J',
    inStock: true,
    stockCount: 35,
  },
  {
    id: '7',
    name: 'Butter Cookies (Limited Edition) 320gm',
    description: 'Classic piped butter cookies with a melt-in-your-mouth texture and a delicate vanilla aroma.',
    price: 55.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['High-Fat Butter', 'Flour', 'Icing Sugar', 'Vanilla Extract'],
    image: 'https://lh3.googleusercontent.com/d/1kWv6pbEOT6_QZbVg6TDp6vGbZhv51to8',
    inStock: true,
    stockCount: 50,
  },
  {
    id: '8',
    name: 'Organic Peanut Cookies 180gm',
    description: 'Traditional round cookies made with aromatic organic peanuts, offering a savory and sweet crunch.',
    price: 28.00,
    category: 'Vegan',
    ingredients: ['Organic Peanuts', 'Peanut Oil', 'Flour', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1ZiEuZXOZqMNWoB4wQ2MFtqU2GAYe_BQM',
    inStock: true,
    stockCount: 40,
  },
  {
    id: '9',
    name: 'Coffee Bean Cookies 160gm',
    description: 'Adorable coffee-bean shaped cookies infused with rich espresso for a bold caffeine kick.',
    price: 28.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Espresso Powder', 'Butter', 'Cocoa Powder', 'Flour', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/19S6QFxCEkBTH0qhkRvC_mk5aWA-wrCVt',
    inStock: true,
    stockCount: 30,
  },
  {
    id: '10',
    name: 'Organic Chocolate Oatmeal + Cacao Nibs 180gm',
    description: 'Hearty oatmeal cookies enriched with dark cacao nibs for texture and deep chocolate intensity.',
    price: 29.00,
    category: 'Vegan',
    ingredients: ['Rolled Oats', 'Cacao Nibs', 'Cocoa Powder', 'Butter', 'Brown Sugar'],
    image: 'https://images.unsplash.com/photo-1557088927-4c07b0eb3c42?q=80&w=800&auto=format&fit=crop',
    inStock: true,
    stockCount: 28,
  },
  {
    id: '11',
    name: 'Coconut Oatmeal Cookies 180gm',
    description: 'Crunchy oatmeal cookies infused with fragrant organic coconut for a tropical twist.',
    price: 27.00,
    category: 'Vegan',
    ingredients: ['Rolled Oats', 'Organic Coconut', 'Flour', 'Coconut Oil', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1yHT5Yk8qEQJbn_zxMJKwUjuDR85IA5B-',
    inStock: true,
    stockCount: 25,
  },
  {
    id: '12',
    name: 'Organic Mixed Spices Cookies 180gm',
    description: 'Aromatic blend of organic spices including cinnamon, nutmeg, and cloves for a warm, festive flavor.',
    price: 28.00,
    category: 'Vegan',
    ingredients: ['Organic Spices', 'Flour', 'Brown Sugar', 'Vegetable Oil'],
    image: 'https://lh3.googleusercontent.com/d/1r_2pqaLTM124LlytVBfXzSL8gcQT-pYE',
    inStock: true,
    stockCount: 30,
  },
  {
    id: '13',
    name: 'Organic Onion Sesame Stick 100gm',
    description: 'Savory sticks made with organic onions and sesame. Contain onion, no egg, no dairy meat.',
    price: 25.00,
    category: 'Organic Five-Spice Vegetarian',
    ingredients: ['Organic Onion', 'Sesame', 'Flour', 'Five Spice', 'Vegetable Oil'],
    image: 'https://lh3.googleusercontent.com/d/1BH35Gku-dZ02P1BVVYTIP-jLq-srzTpc',
    inStock: true,
    stockCount: 20,
  },
  {
    id: '14',
    name: 'Macadamia Rose Cookies 180gm',
    description: 'Delicate cookies infused with organic real rose petals and studded with premium macadamia nuts.',
    price: 32.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Macadamia', 'Real Rose Petals', 'Butter', 'Flour', 'Sugar'],
    image: 'https://lh3.googleusercontent.com/d/1YPpjJDRZN-0yAsWIiGwNbjAnqToiTi04',
    inStock: true,
    stockCount: 25,
  },
  {
    id: '15',
    name: 'Almond Caramel Candy (Toffee) 170gm',
    description: 'Rich, buttery caramel toffee loaded with crunchy roasted almonds.',
    price: 48.00,
    category: 'Butter-Based Vegetarian (No Egg)',
    ingredients: ['Almond', 'Butter', 'Sugar', 'Cream', 'Sea Salt'],
    image: 'https://lh3.googleusercontent.com/d/1eaPZkNl9D97sgktzWfNvNDTSjVJAaTLd',
    inStock: true,
    stockCount: 30,
  }
];